var hierarchy =
[
    [ "AccessMut", null, [
      [ "fgla::AccessConst", "classfgla_1_1AccessConst.html", null ]
    ] ],
    [ "fgla::Adapter", "classfgla_1_1Adapter.html", null ],
    [ "fgla::AspectBits", "structfgla_1_1AspectBits.html", null ],
    [ "fgla::backend::Backend", "structfgla_1_1backend_1_1Backend.html", null ],
    [ "fgla::backend::BackendRegistrar", "structfgla_1_1backend_1_1BackendRegistrar.html", null ],
    [ "fgla::ext::windowing::Capabilities", "structfgla_1_1ext_1_1windowing_1_1Capabilities.html", null ],
    [ "fgla::Color", "structfgla_1_1Color.html", null ],
    [ "fgla::ColorAttachment", "structfgla_1_1ColorAttachment.html", null ],
    [ "fgla::ColorAttachmentDescriptor", "structfgla_1_1ColorAttachmentDescriptor.html", null ],
    [ "fgla::ext::windowing::Configuration", "structfgla_1_1ext_1_1windowing_1_1Configuration.html", null ],
    [ "fgla::Adapter::Descriptor", "structfgla_1_1Adapter_1_1Descriptor.html", null ],
    [ "fgla::Descriptor", "structfgla_1_1Descriptor.html", null ],
    [ "fgla::ext::windowing::Descriptor", "structfgla_1_1ext_1_1windowing_1_1Descriptor.html", null ],
    [ "fgla::Error", "structfgla_1_1Error.html", null ],
    [ "fgla::Extent2d", "structfgla_1_1Extent2d.html", null ],
    [ "fgla::util::FilterableList< T >", "classfgla_1_1util_1_1FilterableList.html", null ],
    [ "fgla::Format", "classfgla_1_1Format.html", null ],
    [ "fgla::util::UUID< size >::Hash", "structfgla_1_1util_1_1UUID_1_1Hash.html", null ],
    [ "std::hash< fgla::Format >", "structstd_1_1hash_3_01fgla_1_1Format_01_4.html", null ],
    [ "fgla::Adapter::Impl", "structfgla_1_1Adapter_1_1Impl.html", null ],
    [ "fgla::Adapter::Info", "structfgla_1_1Adapter_1_1Info.html", null ],
    [ "fgla::LoadOp", "structfgla_1_1LoadOp.html", null ],
    [ "fgla::util::PairHash", "structfgla_1_1util_1_1PairHash.html", null ],
    [ "fgla::ext::windowing::PresentQueueOptions", "structfgla_1_1ext_1_1windowing_1_1PresentQueueOptions.html", null ],
    [ "fgla::PrimitiveState", "structfgla_1_1PrimitiveState.html", null ],
    [ "fgla::ext::windowing::QueueTypeExt", "structfgla_1_1ext_1_1windowing_1_1QueueTypeExt.html", null ],
    [ "fgla::Request", "structfgla_1_1Request.html", null ],
    [ "fgla::Result< T, E >", "classfgla_1_1Result.html", null ],
    [ "fgla::ShaderStage", "structfgla_1_1ShaderStage.html", null ],
    [ "fgla::StoreOp", "structfgla_1_1StoreOp.html", null ],
    [ "fgla::TextureFormatSupportDetails", "structfgla_1_1TextureFormatSupportDetails.html", null ],
    [ "fgla::util::UUID< size >", "structfgla_1_1util_1_1UUID.html", null ],
    [ "fgla::util::UUID< 16 >", "structfgla_1_1util_1_1UUID.html", null ],
    [ "fgla::VersionTriple", "structfgla_1_1VersionTriple.html", null ],
    [ "fgla::ext::windowing::WindowingExtension", "classfgla_1_1ext_1_1windowing_1_1WindowingExtension.html", null ]
];