#pragma once

#include <vector>
#include <array>
#include <variant>
#include <unordered_map>
#include <magic_enum/magic_enum.hpp>

namespace fgla::ext::windowing {

enum class KeyCode {
  Space = 32,
  Apostrophe = 39  /* ' */,
  Comma = 44  /* , */,
  Minus = 45  /* - */,
  Period = 46  /* . */,
  Slash = 47  /* / */,
  _0 = 48,
  _1 = 49,
  _2 = 50,
  _3 = 51,
  _4 = 52,
  _5 = 53,
  _6 = 54,
  _7 = 55,
  _8 = 56,
  _9 = 57,
  Semicolon = 59  /* ; */,
  Equal = 61  /* = */,
  A = 65,
  B = 66,
  C = 67,
  D = 68,
  E = 69,
  F = 70,
  G = 71,
  H = 72,
  I = 73,
  J = 74,
  K = 75,
  L = 76,
  M = 77,
  N = 78,
  O = 79,
  P = 80,
  Q = 81,
  R = 82,
  S = 83,
  T = 84,
  U = 85,
  V = 86,
  W = 87,
  X = 88,
  Y = 89,
  Z = 90,
  LeftBracket = 91  /* [ */,
  Backslash = 92  /* \ */,
  RightBracket = 93  /* ] */,
  GraveAccent = 96  /* ` */,
  World1 = 161  /* non-US #1 */,
  World2 = 162  /* non-US #2 */,
  Escape = 256,
  Enter = 257,
  Tab = 258,
  Backspace = 259,
  Insert = 260,
  Delete = 261,
  Right = 262,
  Left = 263,
  Down = 264,
  Up = 265,
  PageUp = 266,
  PageDown = 267,
  Home = 268,
  End = 269,
  CapsLock = 280,
  ScrollLock = 281,
  NumLock = 282,
  PrintScreen = 283,
  Pause = 284,
  F1 = 290,
  F2 = 291,
  F3 = 292,
  F4 = 293,
  F5 = 294,
  F6 = 295,
  F7 = 296,
  F8 = 297,
  F9 = 298,
  F10 = 299,
  F11 = 300,
  F12 = 301,
  F13 = 302,
  F14 = 303,
  F15 = 304,
  F16 = 305,
  F17 = 306,
  F18 = 307,
  F19 = 308,
  F20 = 309,
  F21 = 310,
  F22 = 311,
  F23 = 312,
  F24 = 313,
  F25 = 314,
  Kp0 = 320,
  Kp1 = 321,
  Kp2 = 322,
  Kp3 = 323,
  Kp4 = 324,
  Kp5 = 325,
  Kp6 = 326,
  Kp7 = 327,
  Kp8 = 328,
  Kp9 = 329,
  KpDecimal = 330,
  KpDivide = 331,
  KpMultiply = 332,
  KpSubtract = 333,
  KpAdd = 334,
  KpEnter = 335,
  KpEqual = 336,
  LeftShift = 340,
  LeftControl = 341,
  LeftAlt = 342,
  LeftSuper = 343,
  RightShift = 344,
  RightControl = 345,
  RightAlt = 346,
  RightSuper = 347,
  Menu = 348,
  MouseLeftButton = -10,
  MouseMiddleButton = -11,
  MouseRightButton = -12
};

constexpr std::array ALL_KEY_CODES{
  KeyCode::Space, KeyCode::Apostrophe, KeyCode::Comma, KeyCode::Minus,
  KeyCode::Period, KeyCode::Slash, KeyCode::_0, KeyCode::_1, KeyCode::_2,
  KeyCode::_3, KeyCode::_4, KeyCode::_5, KeyCode::_6, KeyCode::_7, KeyCode::_8,
  KeyCode::_9, KeyCode::Semicolon, KeyCode::Equal, KeyCode::A, KeyCode::B,
  KeyCode::C, KeyCode::D, KeyCode::E, KeyCode::F, KeyCode::G, KeyCode::H,
  KeyCode::I, KeyCode::J, KeyCode::K, KeyCode::L, KeyCode::M, KeyCode::N,
  KeyCode::O, KeyCode::P, KeyCode::Q, KeyCode::R, KeyCode::S, KeyCode::T,
  KeyCode::U, KeyCode::V, KeyCode::W, KeyCode::X, KeyCode::Y, KeyCode::Z,
  KeyCode::LeftBracket, KeyCode::Backslash, KeyCode::RightBracket,
  KeyCode::GraveAccent, KeyCode::World1, KeyCode::World2, KeyCode::Escape,
  KeyCode::Enter, KeyCode::Tab, KeyCode::Backspace, KeyCode::Insert,
  KeyCode::Delete, KeyCode::Right, KeyCode::Left, KeyCode::Down, KeyCode::Up,
  KeyCode::PageUp, KeyCode::PageDown, KeyCode::Home, KeyCode::End,
  KeyCode::CapsLock, KeyCode::ScrollLock, KeyCode::NumLock,
  KeyCode::PrintScreen, KeyCode::Pause, KeyCode::F1, KeyCode::F2, KeyCode::F3,
  KeyCode::F4, KeyCode::F5, KeyCode::F6, KeyCode::F7, KeyCode::F8, KeyCode::F9,
  KeyCode::F10, KeyCode::F11, KeyCode::F12, KeyCode::F13, KeyCode::F14,
  KeyCode::F15, KeyCode::F16, KeyCode::F17, KeyCode::F18, KeyCode::F19,
  KeyCode::F20, KeyCode::F21, KeyCode::F22, KeyCode::F23, KeyCode::F24,
  KeyCode::F25, KeyCode::Kp0, KeyCode::Kp1, KeyCode::Kp2, KeyCode::Kp3,
  KeyCode::Kp4, KeyCode::Kp5, KeyCode::Kp6, KeyCode::Kp7, KeyCode::Kp8,
  KeyCode::Kp9, KeyCode::KpDecimal, KeyCode::KpDivide, KeyCode::KpMultiply,
  KeyCode::KpSubtract, KeyCode::KpAdd, KeyCode::KpEnter, KeyCode::KpEqual,
  KeyCode::LeftShift, KeyCode::LeftControl, KeyCode::LeftAlt,
  KeyCode::LeftSuper, KeyCode::RightShift, KeyCode::RightControl,
  KeyCode::RightAlt, KeyCode::RightSuper, KeyCode::Menu,
  KeyCode::MouseLeftButton, KeyCode::MouseMiddleButton,
  KeyCode::MouseRightButton
};

static const std::unordered_map<KeyCode, const char*> KEY_CODE_NAMES{
  { KeyCode::Space, "Space" },
  { KeyCode::Apostrophe, "Apostrophe" },
  { KeyCode::Comma, "Comma" },
  { KeyCode::Minus, "Minus" },
  { KeyCode::Period, "Period" },
  { KeyCode::Slash, "Slash" },
  { KeyCode::_0, "0" },
  { KeyCode::_1, "1" },
  { KeyCode::_2, "2" },
  { KeyCode::_3, "3" },
  { KeyCode::_4, "4" },
  { KeyCode::_5, "5" },
  { KeyCode::_6, "6" },
  { KeyCode::_7, "7" },
  { KeyCode::_8, "8" },
  { KeyCode::_9, "9" },
  { KeyCode::Semicolon, "Semicolon" },
  { KeyCode::Equal, "Equal" },
  { KeyCode::A, "A" },
  { KeyCode::B, "B" },
  { KeyCode::C, "C" },
  { KeyCode::D, "D" },
  { KeyCode::E, "E" },
  { KeyCode::F, "F" },
  { KeyCode::G, "G" },
  { KeyCode::H, "H" },
  { KeyCode::I, "I" },
  { KeyCode::J, "J" },
  { KeyCode::K, "K" },
  { KeyCode::L, "L" },
  { KeyCode::M, "M" },
  { KeyCode::N, "N" },
  { KeyCode::O, "O" },
  { KeyCode::P, "P" },
  { KeyCode::Q, "Q" },
  { KeyCode::R, "R" },
  { KeyCode::S, "S" },
  { KeyCode::T, "T" },
  { KeyCode::U, "U" },
  { KeyCode::V, "V" },
  { KeyCode::W, "W" },
  { KeyCode::X, "X" },
  { KeyCode::Y, "Y" },
  { KeyCode::Z, "Z" },
  { KeyCode::LeftBracket, "LeftBracket" },
  { KeyCode::Backslash, "Backslash" },
  { KeyCode::RightBracket, "RightBracket" },
  { KeyCode::GraveAccent, "GraveAccent" },
  { KeyCode::World1, "World1" },
  { KeyCode::World2, "World2" },
  { KeyCode::Escape, "Escape" },
  { KeyCode::Enter, "Enter" },
  { KeyCode::Tab, "Tab" },
  { KeyCode::Backspace, "Backspace" },
  { KeyCode::Insert, "Insert" },
  { KeyCode::Delete, "Delete" },
  { KeyCode::Right, "Right" },
  { KeyCode::Left, "Left" },
  { KeyCode::Down, "Down" },
  { KeyCode::Up, "Up" },
  { KeyCode::PageUp, "PageUp" },
  { KeyCode::PageDown, "PageDown" },
  { KeyCode::Home, "Home" },
  { KeyCode::End, "End" },
  { KeyCode::CapsLock, "CapsLock" },
  { KeyCode::ScrollLock, "ScrollLock" },
  { KeyCode::NumLock, "NumLock" },
  { KeyCode::PrintScreen, "PrintScreen" },
  { KeyCode::Pause, "Pause" },
  { KeyCode::F1, "F1" },
  { KeyCode::F2, "F2" },
  { KeyCode::F3, "F3" },
  { KeyCode::F4, "F4" },
  { KeyCode::F5, "F5" },
  { KeyCode::F6, "F6" },
  { KeyCode::F7, "F7" },
  { KeyCode::F8, "F8" },
  { KeyCode::F9, "F9" },
  { KeyCode::F10, "F10" },
  { KeyCode::F11, "F11" },
  { KeyCode::F12, "F12" },
  { KeyCode::F13, "F13" },
  { KeyCode::F14, "F14" },
  { KeyCode::F15, "F15" },
  { KeyCode::F16, "F16" },
  { KeyCode::F17, "F17" },
  { KeyCode::F18, "F18" },
  { KeyCode::F19, "F19" },
  { KeyCode::F20, "F20" },
  { KeyCode::F21, "F21" },
  { KeyCode::F22, "F22" },
  { KeyCode::F23, "F23" },
  { KeyCode::F24, "F24" },
  { KeyCode::F25, "F25" },
  { KeyCode::Kp0, "Kp0" },
  { KeyCode::Kp1, "Kp1" },
  { KeyCode::Kp2, "Kp2" },
  { KeyCode::Kp3, "Kp3" },
  { KeyCode::Kp4, "Kp4" },
  { KeyCode::Kp5, "Kp5" },
  { KeyCode::Kp6, "Kp6" },
  { KeyCode::Kp7, "Kp7" },
  { KeyCode::Kp8, "Kp8" },
  { KeyCode::Kp9, "Kp9" },
  { KeyCode::KpDecimal, "KpDecimal" },
  { KeyCode::KpDivide, "KpDivide" },
  { KeyCode::KpMultiply, "KpMultiply" },
  { KeyCode::KpSubtract, "KpSubtract" },
  { KeyCode::KpAdd, "KpAdd" },
  { KeyCode::KpEnter, "KpEnter" },
  { KeyCode::KpEqual, "KpEqual" },
  { KeyCode::LeftShift, "LeftShift" },
  { KeyCode::LeftControl, "LeftControl" },
  { KeyCode::LeftAlt, "LeftAlt" },
  { KeyCode::LeftSuper, "LeftSuper" },
  { KeyCode::RightShift, "RightShift" },
  { KeyCode::RightControl, "RightControl" },
  { KeyCode::RightAlt, "RightAlt" },
  { KeyCode::RightSuper, "RightSuper" },
  { KeyCode::Menu, "Menu" },
  { KeyCode::MouseLeftButton, "MouseLeftButton" },
  { KeyCode::MouseMiddleButton, "MouseMiddleButton" },
  { KeyCode::MouseRightButton, "MouseRightButton" }
};

/// A window event emitted when one or more keys were pressed or released since
/// the last poll.
struct KeyEvent {
  std::vector<KeyCode> pressed;
  std::vector<KeyCode> released;
};

/// A window event emitted when the mouse cursor was moved since the last poll.
struct MouseEvent {
  float old_x;
  float old_y;
  float new_x;
  float new_y;
  float delta_x;
  float delta_y;
};

/// A window event
using Event = std::variant<KeyEvent, MouseEvent>;

} // namespace fgla::ext::windowing
